# Generated by Django 3.2.9 on 2021-11-22 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagerApp', '0003_auto_20211121_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='confirm_email',
            field=models.BooleanField(default=False),
        ),
    ]
